# -*- coding: utf-8 -*-
"""Stick_in_the_Pile_GAME_(3).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_2gq2S5Hj7qznrddrUh2qtCkm7qIE2Bu
"""

n = int(input("How many sticks (N) in the pile:  "))
print("There are ",n," sticks in the pile")
name = input("What is your name : ")
count =0 

while  n > 0 :
    yip = input(name +", how many sticks you will take (1 or 2) : ")
    take= int(yip)
    if take <= 0 :
        print("No you cannot take more less than 1 stick!")
    elif take > 2 :
        print("No you cannot take more than 2 sticks!")
    elif take > n :
        print("There are no enough sticks to take.")
    else :      
      n = n-take
      count = count +1               
      if n == 0:
        break
      print("There are",n,"sticks in the pile ")
       
print("OK. There is no stick left in the pile  .You spent ",count,"times.")